# Generated by Django 3.1.2 on 2020-11-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20201020_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='juego',
            field=models.CharField(blank=True, choices=[('E', 'Todos'), ('E+10', 'Todos + 10'), ('T', 'Adolecentes'), ('M', 'Maduro +17'), ('A', 'Adultos +18'), ('RP', 'Clasificacion Pendiente')], default='E', max_length=4),
        ),
    ]
